1 iloc索引的使用

In [7]:
import pandas as pd
ser_obj=pd.Series(range(10,15))
print(ser_obj)
# 对于Series,切片索引与iloc效果相同
# 连续
print(ser_obj[1:3])
print(ser_obj.iloc[1:3])
# 不连续
print(ser_obj[[1,3]])
print(ser_obj.iloc[[1,3]])

0    10
1    11
2    12
3    13
4    14
dtype: int64
1    11
2    12
dtype: int64
1    11
2    12
dtype: int64
1    11
3    13
dtype: int64
1    11
3    13
dtype: int64


In [12]:
import numpy as np
df_obj=pd.DataFrame(np.random.randn(5,4),
                    columns = list('dcba'),
                    index=list('abcde'))
print(df_obj)
# iloc是左闭右开
print(df_obj.iloc[1:3,1:3])
print(df_obj.iloc[:,1:4])
# 不连续
print(df_obj.iloc[:,[1,3]])

          d         c         b         a
a -0.645048  0.559375  0.071133 -0.335587
b -0.650343  1.380415  1.438683  1.891946
c -1.227779  0.824317 -1.495222 -0.990259
d  0.338362 -0.467084 -0.351940 -0.569951
e  0.610133 -0.087485  0.589481  0.245620
          c         b
b  1.380415  1.438683
c  0.824317 -1.495222
          c         b         a
a  0.559375  0.071133 -0.335587
b  1.380415  1.438683  1.891946
c  0.824317 -1.495222 -0.990259
d -0.467084 -0.351940 -0.569951
e -0.087485  0.589481  0.245620
          c         a
a  0.559375 -0.335587
b  1.380415  1.891946
c  0.824317 -0.990259
d -0.467084 -0.569951
e -0.087485  0.245620


2 对齐运算

In [16]:
s1=pd.Series(range(10,20))
s2=pd.Series(range(10,15))
print(s1)
print(s2)
print('-'*50)
print('---对齐运算----')
# 空位默认至nan,运算后,对应位置仍为nan
print(s1+s2)
# 使用padas自带的add方法,设定fill_value来指定对空位的填补值
print(s1.add(s2,fill_value=0))
# 运算后dtype由int64转为float64,空位填补的缘故所在

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64
0    10
1    11
2    12
3    13
4    14
dtype: int64
--------------------------------------------------
---对齐运算----
0    20.0
1    22.0
2    24.0
3    26.0
4    28.0
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
dtype: float64
0    20.0
1    22.0
2    24.0
3    26.0
4    28.0
5    15.0
6    16.0
7    17.0
8    18.0
9    19.0
dtype: float64


In [20]:
df1 = pd.DataFrame(np.ones((2,2)), columns = ['a', 'b'])
df2 = pd.DataFrame(np.ones((3,3)), columns = ['a', 'b', 'c'])
print(df1)
print(df2)
print(df2-df1)
print(df2.sub(df1,fill_value=0))
print(df2.add(df1,fill_value=0))

     a    b
0  1.0  1.0
1  1.0  1.0
     a    b    c
0  1.0  1.0  1.0
1  1.0  1.0  1.0
2  1.0  1.0  1.0
     a    b   c
0  0.0  0.0 NaN
1  0.0  0.0 NaN
2  NaN  NaN NaN
     a    b    c
0  0.0  0.0  1.0
1  0.0  0.0  1.0
2  1.0  1.0  1.0
     a    b    c
0  2.0  2.0  1.0
1  2.0  2.0  1.0
2  1.0  1.0  1.0


3 使用apply和applymap

In [26]:
df = pd.DataFrame(np.random.randn(5,4))
# apply将一个计算应用到所有,默认求列
print(df)
print(df.apply(lambda x : x.max()))
print(df.apply(lambda x : x.min()))

          0         1         2         3
0 -1.401757  0.485250 -0.207846  1.130002
1 -0.247113  1.062433 -0.716560  0.442037
2  0.428540  0.362758  1.099359  0.074602
3 -0.159692 -0.938323  0.698422 -1.149591
4  1.481602 -1.702634  0.875376  0.027397
0    1.481602
1    1.062433
2    1.099359
3    1.130002
dtype: float64
0   -1.401757
1   -1.702634
2   -0.716560
3   -1.149591
dtype: float64


In [27]:
#apply作用在行上
print(df)
print(df.apply(lambda x : x.max(), axis=1))
print(df.apply(lambda x : x.min(), axis=1))

          0         1         2         3
0 -1.401757  0.485250 -0.207846  1.130002
1 -0.247113  1.062433 -0.716560  0.442037
2  0.428540  0.362758  1.099359  0.074602
3 -0.159692 -0.938323  0.698422 -1.149591
4  1.481602 -1.702634  0.875376  0.027397
0    1.130002
1    1.062433
2    1.099359
3    0.698422
4    1.481602
dtype: float64
0   -1.401757
1   -0.716560
2    0.074602
3   -1.149591
4   -1.702634
dtype: float64


In [25]:
# 使用applymap应用到每个数据
print(df)
print(df.applymap(lambda x : '%.2f' % x))
df.dtypes

          0         1         2         3
0 -0.360456 -1.394274 -1.124537 -1.387075
1  0.089309  0.837703 -0.747621  0.783675
2 -0.546141 -1.328510 -0.115747 -0.255823
3  0.038393  0.187356  0.500691  0.469868
4 -1.227689  0.388899  0.281719 -1.758471
       0      1      2      3
0  -0.36  -1.39  -1.12  -1.39
1   0.09   0.84  -0.75   0.78
2  -0.55  -1.33  -0.12  -0.26
3   0.04   0.19   0.50   0.47
4  -1.23   0.39   0.28  -1.76


0    float64
1    float64
2    float64
3    float64
dtype: object

4 对series和df进行按索引排序，按值排序

In [31]:
# Series
s4 = pd.Series(range(10, 15), index = np.random.randint(5, size=5))
print(s4)

# 索引排序,sort_index返回一个新的排好索引的series
print(s4.sort_index())
print(s4) # 原对象未改变
# 设定索引后,仍可以用iloc与切片进行索引,但不可以用loc,因为index值并不唯一
print(s4.iloc[0:3])
s4[0:3]  #默认用的位置索引
# 按值排序
print(s4.sort_values())

4    10
2    11
1    12
3    13
1    14
dtype: int64
1    12
1    14
2    11
3    13
4    10
dtype: int64
4    10
2    11
1    12
3    13
1    14
dtype: int64
4    10
2    11
1    12
dtype: int64
4    10
2    11
1    12
3    13
1    14
dtype: int64


In [29]:
# DataFrame
df4 = pd.DataFrame(np.random.randn(5, 5),
                   index=np.random.randint(5, size=5),
                   columns=np.random.randint(5, size=5))
print(df4)
#轴零是行索引排序,ascending控制升序降序,默认升序
df4_isort = df4.sort_index(axis=0, ascending=False)
print(df4_isort)
#轴1是列索引排序
df4_isort = df4.sort_index(axis=1, ascending=False)
print(df4_isort)

          0         1         3         3         3
0 -0.084820  0.780602  0.626419 -1.580882  0.707254
3  0.802423  0.252576  0.829731 -0.670290 -0.075457
0 -1.494239 -1.699673  0.514283 -0.096885 -0.004610
3 -0.528591  1.138616  0.654720 -0.408526 -1.068302
3 -0.043488  0.214707 -0.360127 -0.369138 -0.835935
          0         1         3         3         3
3  0.802423  0.252576  0.829731 -0.670290 -0.075457
3 -0.528591  1.138616  0.654720 -0.408526 -1.068302
3 -0.043488  0.214707 -0.360127 -0.369138 -0.835935
0 -0.084820  0.780602  0.626419 -1.580882  0.707254
0 -1.494239 -1.699673  0.514283 -0.096885 -0.004610
          3         3         3         1         0
0  0.626419 -1.580882  0.707254  0.780602 -0.084820
3  0.829731 -0.670290 -0.075457  0.252576  0.802423
0  0.514283 -0.096885 -0.004610 -1.699673 -1.494239
3  0.654720 -0.408526 -1.068302  1.138616 -0.528591
3 -0.360127 -0.369138 -0.835935  0.214707 -0.043488


In [34]:
# 按值排序,by后是column的值
import random
l=[random.randint(0,100) for i in range(24)]
df4 = pd.DataFrame(np.array(l).reshape(6,4))
print(df4.values)
print('-'*50)
print(df4)
print('-'*50)
#按轴零排序，by后是列名
df4_vsort = df4.sort_values(by=3,axis=0, ascending=False) #寻找的是columns里的3
print(df4_vsort)
#按轴1排序，by后行索引名
df4_vsort = df4.sort_values(by=3,axis=1, ascending=False) #寻找的是index里的3
print(df4_vsort)

[[29 53 20 76]
 [47 37 15 64]
 [80 48 97 43]
 [86 96 91 81]
 [43 36 76 83]
 [61 18 36 46]]
--------------------------------------------------
    0   1   2   3
0  29  53  20  76
1  47  37  15  64
2  80  48  97  43
3  86  96  91  81
4  43  36  76  83
5  61  18  36  46
--------------------------------------------------
    0   1   2   3
4  43  36  76  83
3  86  96  91  81
0  29  53  20  76
1  47  37  15  64
5  61  18  36  46
2  80  48  97  43
    1   2   0   3
0  53  20  29  76
1  37  15  47  64
2  48  97  80  43
3  96  91  86  81
4  36  76  43  83
5  18  36  61  46


5 缺失数据处理方法

In [35]:
df_data = pd.DataFrame([np.random.randn(3), [1., 2., np.nan],
                       [np.nan, 4., np.nan], [1., 2., 3.]])
print(df_data.head())

          0         1         2
0  0.323127  0.487345 -1.071798
1  1.000000  2.000000       NaN
2       NaN  4.000000       NaN
3  1.000000  2.000000  3.000000


In [36]:
# isnull来判断是否有空的数据
print(df_data.isnull())

       0      1      2
0  False  False  False
1  False  False   True
2   True  False   True
3  False  False  False


In [37]:
# dropna默认某行有nan就删除该行
print(df_data.dropna())

          0         1         2
0  0.323127  0.487345 -1.071798
3  1.000000  2.000000  3.000000


In [38]:
# 某个特征column空值太多时使用
print(df_data.dropna(axis=1))  #某列有nan就删除该列

          1
0  0.487345
1  2.000000
2  4.000000
3  2.000000


In [39]:
# inplace测试,为True则原地删除改变
test_data=pd.DataFrame([np.random.randn(3), [1., 2., np.nan],
                       [np.nan, 4., np.nan], [1., 2., 3.]])
test_data.dropna(inplace=True)
print(test_data)

          0         1         2
0  1.214743 -0.205925  0.095595
3  1.000000  2.000000  3.000000


In [40]:
#给零列的空值填为-100
print(df_data.iloc[:,0].fillna(-100.))

0      0.323127
1      1.000000
2   -100.000000
3      1.000000
Name: 0, dtype: float64


In [42]:
# 依次拿到每一列,columns得到的是列名,非索引值
# 再对每一列的nan改为99
for i in df_data.columns:
    print(i)
    print(df_data.loc[:,i].fillna(99.))

0
0     0.323127
1     1.000000
2    99.000000
3     1.000000
Name: 0, dtype: float64
1
0    0.487345
1    2.000000
2    4.000000
3    2.000000
Name: 1, dtype: float64
2
0    -1.071798
1    99.000000
2    99.000000
3     3.000000
Name: 2, dtype: float64


6 层级索引（hierarchical indexing）

In [43]:
import pandas as pd
import numpy as np

#MultiIndex是层级索引，索引类型的一种
index1 = pd.MultiIndex.from_arrays([['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'c', 'd', 'd', 'd'],
                [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]], names=['cloth', 'size'])


ser_obj = pd.Series(np.random.randn(12),index=index1)
print(ser_obj)
print(type(ser_obj))
print(type(ser_obj.index))
print(ser_obj.index)
print(ser_obj.index.levels)

cloth  size
a      0      -0.405727
       1       0.182779
       2       0.024131
b      0      -0.864360
       1      -0.347575
       2       0.081265
c      0       1.237891
       1      -0.475260
       2      -0.510027
d      0       0.668664
       1       0.171535
       2      -0.622929
dtype: float64
<class 'pandas.core.series.Series'>
<class 'pandas.core.indexes.multi.MultiIndex'>
MultiIndex([('a', 0),
            ('a', 1),
            ('a', 2),
            ('b', 0),
            ('b', 1),
            ('b', 2),
            ('c', 0),
            ('c', 1),
            ('c', 2),
            ('d', 0),
            ('d', 1),
            ('d', 2)],
           names=['cloth', 'size'])
[['a', 'b', 'c', 'd'], [0, 1, 2]]


FrozenList([[0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3], [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]])

In [44]:
#层级索引如何取数据
print(ser_obj)
print('-'*50)
# 获取所有cloth索引为c的数据
print(ser_obj['c'])
print('-'*50)
print(ser_obj['a', 2])
print('-'*50)
# 获取所有size索引为2的数据
print(ser_obj[:, 2])

cloth  size
a      0      -0.405727
       1       0.182779
       2       0.024131
b      0      -0.864360
       1      -0.347575
       2       0.081265
c      0       1.237891
       1      -0.475260
       2      -0.510027
d      0       0.668664
       1       0.171535
       2      -0.622929
dtype: float64
--------------------------------------------------
size
0    1.237891
1   -0.475260
2   -0.510027
dtype: float64
--------------------------------------------------
0.02413148302437681
--------------------------------------------------
cloth
a    0.024131
b    0.081265
c   -0.510027
d   -0.622929
dtype: float64


In [45]:
#交换层级
# 得到一个新的对象
print(ser_obj.swaplevel())
print('-'*50)
# 原对象并未发生改变
print(ser_obj)
print('-'* 50)

size  cloth
0     a       -0.405727
1     a        0.182779
2     a        0.024131
0     b       -0.864360
1     b       -0.347575
2     b        0.081265
0     c        1.237891
1     c       -0.475260
2     c       -0.510027
0     d        0.668664
1     d        0.171535
2     d       -0.622929
dtype: float64
--------------------------------------------------
cloth  size
a      0      -0.405727
       1       0.182779
       2       0.024131
b      0      -0.864360
       1      -0.347575
       2       0.081265
c      0       1.237891
       1      -0.475260
       2      -0.510027
d      0       0.668664
       1       0.171535
       2      -0.622929
dtype: float64
--------------------------------------------------


In [55]:
ser_obj=ser_obj.swaplevel()
print(ser_obj)
# level=0即按照第一层索引级别
print(ser_obj.sort_index(level=0))  #层级索引按那个索引级别排序
#把0索引（最外层索引）变为列索引
# 默认-1,即内层索引
df_obj=ser_obj.unstack(0)  #unstack可以放索引名，或者索引位置
print(df_obj)


cloth  size
a      0      -0.405727
       1       0.182779
       2       0.024131
b      0      -0.864360
       1      -0.347575
       2       0.081265
c      0       1.237891
       1      -0.475260
       2      -0.510027
d      0       0.668664
       1       0.171535
       2      -0.622929
dtype: float64
cloth  size
a      0      -0.405727
       1       0.182779
       2       0.024131
b      0      -0.864360
       1      -0.347575
       2       0.081265
c      0       1.237891
       1      -0.475260
       2      -0.510027
d      0       0.668664
       1       0.171535
       2      -0.622929
dtype: float64
cloth         a         b         c         d
size                                         
0     -0.405727 -0.864360  1.237891  0.668664
1      0.182779 -0.347575 -0.475260  0.171535
2      0.024131  0.081265 -0.510027 -0.622929


In [54]:
#对df进行stack，就会把行，列索引进行堆叠，变为series
df_obj.stack()  #stack变为series和unstack保持一致的

cloth  size
a      0      -0.405727
       1       0.182779
       2       0.024131
b      0      -0.864360
       1      -0.347575
       2       0.081265
c      0       1.237891
       1      -0.475260
       2      -0.510027
d      0       0.668664
       1       0.171535
       2      -0.622929
dtype: float64

7 Pandas统计计算和描述

In [56]:
print(df_obj)
df_obj.loc[0,'b']=np.nan
print(df_obj)
print('-'*50)
print(df_obj.min(axis=0, skipna=True))
print('-'*50)
print(df_obj.describe())  #观察数据分布的一种方法

cloth         a         b         c         d
size                                         
0     -0.405727 -0.864360  1.237891  0.668664
1      0.182779 -0.347575 -0.475260  0.171535
2      0.024131  0.081265 -0.510027 -0.622929
cloth         a         b         c         d
size                                         
0     -0.405727       NaN  1.237891  0.668664
1      0.182779 -0.347575 -0.475260  0.171535
2      0.024131  0.081265 -0.510027 -0.622929
--------------------------------------------------
cloth
a   -0.405727
b   -0.347575
c   -0.510027
d   -0.622929
dtype: float64
--------------------------------------------------
cloth         a         b         c         d
count  3.000000  2.000000  3.000000  3.000000
mean  -0.066272 -0.133155  0.084202  0.072423
std    0.304491  0.303235  0.999276  0.651476
min   -0.405727 -0.347575 -0.510027 -0.622929
25%   -0.190798 -0.240365 -0.492643 -0.225697
50%    0.024131 -0.133155 -0.475260  0.171535
75%    0.103455 -0.025945  0.381316  0.

In [57]:
df_obj.loc[:,'c']

size
0    1.237891
1   -0.475260
2   -0.510027
Name: c, dtype: float64

In [58]:
#计算最小值或者最大值的索引的位置
print(df_obj.loc[:,'c'].argmin())#argmin和argmax只能是series，不能是df


2


In [59]:
#返回的是一个series
df_obj.idxmin(axis=1)  #计算最小值或者最大值的索引值
df_obj.idxmax(axis=1)  #计算最小值或者最大值的索引值

size
0    c
1    a
2    b
dtype: object

电影数据分析

In [60]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

file_path = "IMDB-Movie-Data.csv"
df = pd.read_csv(file_path) #不加路径默认当前路径
print(df)

     Rank                    Title                     Genre  \
0       1  Guardians of the Galaxy   Action,Adventure,Sci-Fi   
1       2               Prometheus  Adventure,Mystery,Sci-Fi   
2       3                    Split           Horror,Thriller   
3       4                     Sing   Animation,Comedy,Family   
4       5            Suicide Squad  Action,Adventure,Fantasy   
..    ...                      ...                       ...   
995   996     Secret in Their Eyes       Crime,Drama,Mystery   
996   997          Hostel: Part II                    Horror   
997   998   Step Up 2: The Streets       Drama,Music,Romance   
998   999             Search Party          Adventure,Comedy   
999  1000               Nine Lives     Comedy,Family,Fantasy   

                                           Description              Director  \
0    A group of intergalactic criminals are forced ...            James Gunn   
1    Following clues to the origin of mankind, a te...          Ridley 